# Remix display version
REMIX_DISPLAY_VERSION = $(PRODUCT_VERSION_MAJOR)-$(LINEAGE_BUILD_DATE)-$(LINEAGE_BUILDTYPE)$(LINEAGE_EXTRAVERSION)-REMIX-$(LINEAGE_BUILD)

# Remix revision
REMIX_REVISION_TITLE = niceparse.Four_(Druiswurm)
REMIX_REVISION_SUMMARY = https://github.com/plros
